#activemq:
#  image: webcenter/activemq:latest
#  ports:
#    - 8161:8161
#    - 61616:61616
#    - 61613:61613
#  extends:
#    file: activemq.yml
#    service: activemq_base
#  volumes:
#    - /container_data/activemq/data:/data/activemq
#    - /container_data/activemq/log:/var/log/activemq
transgen:
  extends:
    file: activemq.yml
    service: activemq_base
  build: .
  ports:
    - "8080:8080"
#  links:
#    - activemq:activemq
  volumes:
    - ./storage:/storage